//! Red Queen Evolution — Adversarial co-evolving test suite for scp-queue.
//!
//! Generated by deterministic adversarial evolution protocol.
//! These tests target mutation-surviving code paths, missing invariants,
//! and edge cases not covered by the existing 652-test suite.

#![deny(clippy::unwrap_used)]
#![deny(clippy::expect_used)]
#![deny(clippy::panic)]
#![forbid(unsafe_code)]

use scp_queue::domain::queue::{Queue, QueueEntry, QueueStatus};
use scp_queue::domain::validation::{ValidationError, ValidationResult, Validator};
use scp_queue::domain::identifiers::{QueueEntryId, SessionName};
use scp_queue::MAX_PRIORITY;

// =========================================================================
// DIMENSION: state-machine-exhaustive
// =========================================================================

#[test]
fn rq_state_machine_self_transitions_all_rejected() {
    let all = [
        QueueStatus::Pending,
        QueueStatus::Claimed,
        QueueStatus::Rebasing,
        QueueStatus::Testing,
        QueueStatus::ReadyToMerge,
        QueueStatus::Merging,
        QueueStatus::Merged,
        QueueStatus::FailedRetryable,
        QueueStatus::FailedTerminal,
        QueueStatus::Cancelled,
    ];
    for status in &all {
        let result = status.transition_to(*status);
        assert!(
            result.is_err(),
            "Self-transition {:?} -> {:?} should be rejected",
            status,
            status
        );
    }
}

#[test]
fn rq_state_machine_reverse_happy_path_rejected() {
    let reverse = [
        (QueueStatus::Claimed, QueueStatus::Pending),
        (QueueStatus::Rebasing, QueueStatus::Claimed),
        (QueueStatus::Testing, QueueStatus::Rebasing),
        (QueueStatus::ReadyToMerge, QueueStatus::Testing),
        (QueueStatus::Merging, QueueStatus::ReadyToMerge),
    ];
    for (from, to) in &reverse {
        assert!(
            from.transition_to(*to).is_err(),
            "Reverse transition {:?} -> {:?} should be rejected",
            from,
            to
        );
    }
}

#[test]
fn rq_state_machine_skip_ahead_rejected() {
    let skips = [
        (QueueStatus::Pending, QueueStatus::Rebasing),
        (QueueStatus::Pending, QueueStatus::Testing),
        (QueueStatus::Pending, QueueStatus::ReadyToMerge),
        (QueueStatus::Pending, QueueStatus::Merging),
        (QueueStatus::Pending, QueueStatus::Merged),
        (QueueStatus::Claimed, QueueStatus::Testing),
        (QueueStatus::Claimed, QueueStatus::ReadyToMerge),
        (QueueStatus::Claimed, QueueStatus::Merging),
        (QueueStatus::Claimed, QueueStatus::Merged),
        (QueueStatus::Rebasing, QueueStatus::ReadyToMerge),
        (QueueStatus::Rebasing, QueueStatus::Merging),
        (QueueStatus::Rebasing, QueueStatus::Merged),
        (QueueStatus::Testing, QueueStatus::Merging),
        (QueueStatus::Testing, QueueStatus::Merged),
        (QueueStatus::ReadyToMerge, QueueStatus::Merged),
    ];
    for (from, to) in &skips {
        assert!(
            from.transition_to(*to).is_err(),
            "Skip-ahead {:?} -> {:?} should be rejected",
            from,
            to
        );
    }
}

#[test]
fn rq_state_machine_failed_terminal_to_pending_rejected() {
    assert!(QueueStatus::FailedTerminal.transition_to(QueueStatus::Pending).is_err());
}

#[test]
fn rq_state_machine_failed_terminal_to_claimed_rejected() {
    assert!(QueueStatus::FailedTerminal.transition_to(QueueStatus::Claimed).is_err());
}

#[test]
fn rq_state_machine_failed_terminal_to_retryable_rejected() {
    assert!(QueueStatus::FailedTerminal.transition_to(QueueStatus::FailedRetryable).is_err());
}

#[test]
fn rq_state_machine_transition_to_returns_correct_status() {
    let result = QueueStatus::Pending.transition_to(QueueStatus::Claimed);
    assert_eq!(result.unwrap(), QueueStatus::Claimed);

    let result = QueueStatus::Merging.transition_to(QueueStatus::Merged);
    assert_eq!(result.unwrap(), QueueStatus::Merged);

    let result = QueueStatus::Testing.transition_to(QueueStatus::FailedRetryable);
    assert_eq!(result.unwrap(), QueueStatus::FailedRetryable);
}

#[test]
fn rq_state_machine_exhaustive_10x10_cross_product() {
    let all = [
        QueueStatus::Pending,
        QueueStatus::Claimed,
        QueueStatus::Rebasing,
        QueueStatus::Testing,
        QueueStatus::ReadyToMerge,
        QueueStatus::Merging,
        QueueStatus::Merged,
        QueueStatus::FailedRetryable,
        QueueStatus::FailedTerminal,
        QueueStatus::Cancelled,
    ];

    // Known valid transitions
    let valid: std::collections::HashSet<(QueueStatus, QueueStatus)> = [
        (QueueStatus::Pending, QueueStatus::Claimed),
        (QueueStatus::Pending, QueueStatus::Cancelled),
        (QueueStatus::Claimed, QueueStatus::Rebasing),
        (QueueStatus::Claimed, QueueStatus::Cancelled),
        (QueueStatus::Rebasing, QueueStatus::Testing),
        (QueueStatus::Rebasing, QueueStatus::Cancelled),
        (QueueStatus::Testing, QueueStatus::ReadyToMerge),
        (QueueStatus::Testing, QueueStatus::FailedRetryable),
        (QueueStatus::Testing, QueueStatus::FailedTerminal),
        (QueueStatus::Testing, QueueStatus::Cancelled),
        (QueueStatus::ReadyToMerge, QueueStatus::Merging),
        (QueueStatus::ReadyToMerge, QueueStatus::Cancelled),
        (QueueStatus::Merging, QueueStatus::Merged),
        (QueueStatus::Merging, QueueStatus::Cancelled),
        (QueueStatus::FailedRetryable, QueueStatus::Pending),
        (QueueStatus::FailedRetryable, QueueStatus::Cancelled),
    ]
    .into_iter()
    .collect();

    for from in &all {
        for to in &all {
            let result = from.transition_to(*to);
            if valid.contains(&(*from, *to)) {
                assert!(result.is_ok(), "Expected valid: {:?} -> {:?}", from, to);
                assert_eq!(result.unwrap(), *to);
            } else {
                assert!(result.is_err(), "Expected invalid: {:?} -> {:?}", from, to);
            }
        }
    }
}

#[test]
fn rq_state_machine_is_failed_consistent() {
    assert!(QueueStatus::FailedRetryable.is_failed());
    assert!(QueueStatus::FailedTerminal.is_failed());
    assert!(!QueueStatus::Pending.is_failed());
    assert!(!QueueStatus::Claimed.is_failed());
    assert!(!QueueStatus::Rebasing.is_failed());
    assert!(!QueueStatus::Testing.is_failed());
    assert!(!QueueStatus::ReadyToMerge.is_failed());
    assert!(!QueueStatus::Merging.is_failed());
    assert!(!QueueStatus::Merged.is_failed());
    assert!(!QueueStatus::Cancelled.is_failed());
}

// =========================================================================
// DIMENSION: invariants-priority-ordering
// =========================================================================

#[test]
fn rq_priority_ordering_after_dequeue_front() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("a", "s-a", 10).unwrap())
        .enqueue(QueueEntry::new("b", "s-b", 20).unwrap())
        .enqueue(QueueEntry::new("c", "s-c", 30).unwrap());

    let id_a = QueueEntryId::new("a").unwrap();
    let (queue, removed) = queue.dequeue(&id_a);
    assert!(removed.is_some());
    assert_eq!(queue.len(), 2);

    // Verify ordering preserved after removal
    let priorities: Vec<u32> = queue.entries().iter().map(|e| e.priority).collect();
    for window in priorities.windows(2) {
        assert!(window[0] <= window[1], "Priority ordering violated: {:?}", window);
    }
}

#[test]
fn rq_priority_ordering_after_dequeue_middle() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("a", "s-a", 10).unwrap())
        .enqueue(QueueEntry::new("b", "s-b", 20).unwrap())
        .enqueue(QueueEntry::new("c", "s-c", 30).unwrap());

    let id_b = QueueEntryId::new("b").unwrap();
    let (queue, removed) = queue.dequeue(&id_b);
    assert!(removed.is_some());
    assert_eq!(queue.len(), 2);

    let priorities: Vec<u32> = queue.entries().iter().map(|e| e.priority).collect();
    for window in priorities.windows(2) {
        assert!(window[0] <= window[1], "Priority ordering violated after middle dequeue");
    }
}

#[test]
fn rq_priority_ordering_after_dequeue_last() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("a", "s-a", 10).unwrap())
        .enqueue(QueueEntry::new("b", "s-b", 20).unwrap())
        .enqueue(QueueEntry::new("c", "s-c", 30).unwrap());

    let id_c = QueueEntryId::new("c").unwrap();
    let (queue, removed) = queue.dequeue(&id_c);
    assert!(removed.is_some());
    assert_eq!(queue.len(), 2);

    let priorities: Vec<u32> = queue.entries().iter().map(|e| e.priority).collect();
    for window in priorities.windows(2) {
        assert!(window[0] <= window[1], "Priority ordering violated after last dequeue");
    }
}

#[test]
fn rq_fifo_preserved_under_interleaved_operations() {
    // Insert entries with same priority, dequeue middle, re-insert
    let queue = Queue::new()
        .enqueue(QueueEntry::new("a", "s-a", 50).unwrap())
        .enqueue(QueueEntry::new("b", "s-b", 50).unwrap())
        .enqueue(QueueEntry::new("c", "s-c", 50).unwrap());

    let id_b = QueueEntryId::new("b").unwrap();
    let (queue, _) = queue.dequeue(&id_b);

    // Re-insert b at same priority
    let queue = queue.enqueue(QueueEntry::new("b", "s-b", 50).unwrap());

    let ids: Vec<&str> = queue.entries().iter().map(|e| e.id.as_str()).collect();
    // After re-insertion, b should be after c (FIFO within same priority)
    assert_eq!(ids, vec!["a", "c", "b"], "FIFO violated after re-insertion");
}

#[test]
fn rq_priority_invariant_after_many_enqueue_dequeue_cycles() {
    let mut queue = Queue::new();
    for i in 0..100 {
        let id = format!("e-{}", i);
        let session = format!("s-{}", i);
        queue = queue.enqueue(QueueEntry::new(&id, &session, (i % 50) as u32).unwrap());
    }

    // Dequeue every other entry
    for i in 0..100 {
        if i % 2 == 0 {
            let id = QueueEntryId::new(format!("e-{}", i)).unwrap();
            let (q, _) = queue.dequeue(&id);
            queue = q;
        }
    }

    // Verify priority ordering still holds
    let priorities: Vec<u32> = queue.entries().iter().map(|e| e.priority).collect();
    for window in priorities.windows(2) {
        assert!(window[0] <= window[1], "Priority ordering violated after cycles: {:?}", window);
    }
}

#[test]
fn rq_enqueue_at_boundaries_preserves_ordering() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("min", "s-min", 0).unwrap())
        .enqueue(QueueEntry::new("max", "s-max", MAX_PRIORITY).unwrap())
        .enqueue(QueueEntry::new("mid", "s-mid", 50).unwrap());

    let priorities: Vec<u32> = queue.entries().iter().map(|e| e.priority).collect();
    for window in priorities.windows(2) {
        assert!(window[0] <= window[1]);
    }
    assert_eq!(priorities[0], 0);
    assert_eq!(*priorities.last().unwrap(), MAX_PRIORITY);
}

// =========================================================================
// DIMENSION: invariants-count-consistency
// =========================================================================

#[test]
fn rq_len_matches_entries_after_operations() {
    let mut queue = Queue::new();
    assert_eq!(queue.len(), queue.entries().len());

    for i in 0..20 {
        let id = format!("e-{}", i);
        queue = queue.enqueue(QueueEntry::new(&id, &id, (i % 10) as u32).unwrap());
        assert_eq!(queue.len(), queue.entries().len());
    }

    for i in 0..10 {
        let id = QueueEntryId::new(format!("e-{}", i)).unwrap();
        let (q, _) = queue.dequeue(&id);
        queue = q;
        assert_eq!(queue.len(), queue.entries().len());
    }

    for i in 10..20 {
        let id = QueueEntryId::new(format!("e-{}", i)).unwrap();
        let q = queue.update_status(&id, QueueStatus::Claimed).unwrap();
        queue = q;
        assert_eq!(queue.len(), queue.entries().len());
    }
}

#[test]
fn rq_count_active_vs_manual_count() {
    let merged = QueueEntry::new("c", "s-c", 30)
        .unwrap()
        .transition_status(QueueStatus::Claimed)
        .unwrap()
        .transition_status(QueueStatus::Rebasing)
        .unwrap()
        .transition_status(QueueStatus::Testing)
        .unwrap()
        .transition_status(QueueStatus::ReadyToMerge)
        .unwrap()
        .transition_status(QueueStatus::Merging)
        .unwrap()
        .transition_status(QueueStatus::Merged)
        .unwrap();

    let queue = Queue::new()
        .enqueue(QueueEntry::new("a", "s-a", 10).unwrap())
        .enqueue(
            QueueEntry::new("b", "s-b", 20)
                .unwrap()
                .transition_status(QueueStatus::Claimed)
                .unwrap(),
        )
        .enqueue(merged)
        .enqueue(
            QueueEntry::new("d", "s-d", 40)
                .unwrap()
                .transition_status(QueueStatus::Cancelled)
                .unwrap(),
        );

    let manual_active = queue
        .entries()
        .iter()
        .filter(|e| !e.status.is_terminal())
        .count();

    assert_eq!(queue.count_active(), manual_active);
    assert_eq!(queue.count_active(), 2); // Pending + Claimed
}

#[test]
fn rq_is_empty_consistent_with_len() {
    let queue = Queue::new();
    assert!(queue.is_empty());
    assert_eq!(queue.len(), 0);

    let queue = queue.enqueue(QueueEntry::new("e1", "s1", 10).unwrap());
    assert!(!queue.is_empty());
    assert_eq!(queue.len(), 1);

    let id = QueueEntryId::new("e1").unwrap();
    let (queue, _) = queue.dequeue(&id);
    assert!(queue.is_empty());
    assert_eq!(queue.len(), 0);
}

// =========================================================================
// DIMENSION: validation-edge-cases
// =========================================================================

#[test]
fn rq_validator_finalize_returns_ok_when_empty() {
    let v = Validator::new();
    assert!(v.finalize().is_ok());
}

#[test]
fn rq_validator_validate_preserves_value_on_success() {
    let mut v = Validator::new();
    let result = v.validate(Ok("preserved".to_string()));
    assert_eq!(result, Some("preserved".to_string()));
}

#[test]
fn rq_validator_check_true_returns_ok() {
    let mut v = Validator::new();
    let result = v.check(true, ValidationError::EmptyValue("x".into()));
    assert!(result.is_ok());
    assert!(!v.has_errors());
}

#[test]
fn rq_validator_check_false_collects_error() {
    let mut v = Validator::new();
    let result = v.check(false, ValidationError::EmptyValue("check-fail".into()));
    assert!(result.is_err());
    assert!(v.has_errors());
    assert_eq!(v.error_count(), 1);
}

#[test]
fn rq_validator_multiple_check_errors() {
    let mut v = Validator::new();
    let _ = v.check(false, ValidationError::EmptyValue("a".into()));
    let _ = v.check(false, ValidationError::EmptyValue("b".into()));
    let _ = v.check(false, ValidationError::EmptyValue("c".into()));
    assert_eq!(v.error_count(), 3);

    let result = v.finalize();
    assert!(matches!(result, Err(ValidationError::Multiple(_))));
    if let Err(ValidationError::Multiple(errors)) = result {
        assert_eq!(errors.len(), 3);
    }
}

#[test]
fn rq_validate_range_exact_boundary_min() {
    assert!(scp_queue::domain::validation::validate_range(0, 0, 100, "test").is_ok());
}

#[test]
fn rq_validate_range_exact_boundary_max() {
    assert!(scp_queue::domain::validation::validate_range(100, 0, 100, "test").is_ok());
}

#[test]
fn rq_validate_all_empty_returns_ok() {
    let result: ValidationResult<Vec<String>> = scp_queue::domain::validation::validate_all(vec![]);
    assert!(result.is_ok());
    assert!(result.unwrap().is_empty());
}

#[test]
fn rq_validate_all_with_errors_returns_first_error() {
    let results = vec![
        Ok(1),
        Err(ValidationError::EmptyValue("first-err".into())),
        Err(ValidationError::EmptyValue("second-err".into())),
    ];
    let result = scp_queue::domain::validation::validate_all(results);
    assert!(result.is_err());
    if let Err(ValidationError::EmptyValue(field)) = result {
        assert_eq!(field, "first-err");
    }
}

#[test]
fn rq_validate_that_preserves_value() {
    let val = 42i32;
    let result = scp_queue::domain::validation::validate_that(val, |&v| v == 42, "test");
    assert_eq!(result.unwrap(), 42);
}

#[test]
fn rq_validation_error_is_recoverable_all_variants() {
    // Recoverable
    assert!(ValidationError::EmptyValue("x".into()).is_recoverable());
    assert!(ValidationError::InvalidCharacters { field: "f".into(), found: "c".into() }.is_recoverable());
    assert!(ValidationError::OutOfBounds { position: 0, length: 0 }.is_recoverable());

    // NOT recoverable
    assert!(!ValidationError::ExceedsMaximum { field: "f".into(), value: 0, max: 0 }.is_recoverable());
    assert!(!ValidationError::BelowMinimum { field: "f".into(), value: 0, min: 0 }.is_recoverable());
    assert!(!ValidationError::InvalidStateTransition { from: "A".into(), to: "B".into() }.is_recoverable());
    assert!(!ValidationError::NotFound { field: "f".into(), value: "v".into() }.is_recoverable());
    assert!(!ValidationError::AlreadyExists { field: "f".into(), value: "v".into() }.is_recoverable());
    assert!(!ValidationError::Multiple(vec![]).is_recoverable());
}

// =========================================================================
// DIMENSION: identifier-injection
// =========================================================================

#[test]
fn rq_session_name_rejects_null_byte_at_start() {
    assert!(SessionName::new("\x00session").is_err());
}

#[test]
fn rq_session_name_rejects_null_byte_at_end() {
    assert!(SessionName::new("session\x00").is_err());
}

#[test]
fn rq_session_name_rejects_null_byte_in_middle() {
    assert!(SessionName::new("ses\x00ion").is_err());
}

#[test]
fn rq_session_name_rejects_backtick() {
    assert!(SessionName::new("ses`ion").is_err());
}

#[test]
fn rq_session_name_rejects_pipe() {
    assert!(SessionName::new("ses|ion").is_err());
}

#[test]
fn rq_session_name_rejects_ampersand() {
    assert!(SessionName::new("ses&ion").is_err());
}

#[test]
fn rq_session_name_rejects_angle_brackets() {
    assert!(SessionName::new("ses<ion").is_err());
    assert!(SessionName::new("ses>ion").is_err());
}

#[test]
fn rq_session_name_accepts_dots_dashes_underscores() {
    assert!(SessionName::new("a.b-c_d").is_ok());
}

#[test]
fn rq_session_name_accepts_numbers() {
    assert!(SessionName::new("session-123").is_ok());
}

#[test]
fn rq_queue_entry_id_does_not_trim() {
    // QueueEntryId should NOT trim — only SessionName trims
    let id = QueueEntryId::new("  spaced  ").unwrap();
    assert_eq!(id.as_str(), "  spaced  ");
}

#[test]
fn rq_queue_entry_id_accepts_special_chars() {
    // QueueEntryId only rejects empty/whitespace
    assert!(QueueEntryId::new("id-with_special!@#$%").is_ok());
}

#[test]
fn rq_session_name_rejects_tab() {
    // Tab is not in SHELL_METACHARACTERS but let's verify behavior
    let result = SessionName::new("ses\tion");
    // Tab gets trimmed by .trim() if at edges, or passes if in middle
    // The key invariant: the result should be deterministic
    let _ = result; // Just verify it doesn't panic
}

// =========================================================================
// DIMENSION: queue-immutable-semantics
// =========================================================================

#[test]
fn rq_enqueue_does_not_mutate_original() {
    let queue = Queue::new();
    let entry = QueueEntry::new("e1", "s1", 10).unwrap();
    let _new_queue = queue.enqueue(entry);
    assert!(queue.is_empty(), "Original queue must remain empty after enqueue");
}

#[test]
fn rq_dequeue_does_not_mutate_original() {
    let queue = Queue::new().enqueue(QueueEntry::new("e1", "s1", 10).unwrap());
    let id = QueueEntryId::new("e1").unwrap();
    let (_new, removed) = queue.dequeue(&id);
    assert!(removed.is_some(), "Dequeue should find the entry");
    assert_eq!(queue.len(), 1, "Original queue must still have 1 entry");
}

#[test]
fn rq_update_status_does_not_mutate_original() {
    let queue = Queue::new().enqueue(QueueEntry::new("e1", "s1", 10).unwrap());
    let id = QueueEntryId::new("e1").unwrap();
    let result = queue.update_status(&id, QueueStatus::Claimed);
    assert!(result.is_ok());
    // Original should still have Pending
    assert_eq!(queue.find(&id).unwrap().status, QueueStatus::Pending);
    assert_eq!(result.unwrap().find(&id).unwrap().status, QueueStatus::Claimed);
}

#[test]
fn rq_remove_at_does_not_mutate_original() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("a", "s-a", 10).unwrap())
        .enqueue(QueueEntry::new("b", "s-b", 20).unwrap());
    let result = queue.remove_at(0);
    assert!(result.is_ok());
    assert_eq!(queue.len(), 2, "Original queue must still have 2 entries");
}

#[test]
fn rq_with_entry_does_not_mutate_original() {
    let queue = Queue::new().enqueue(QueueEntry::new("a", "s-a", 10).unwrap());
    let new_entry = QueueEntry::new("b", "s-b", 20).unwrap();
    let result = queue.with_entry(1, new_entry);
    assert!(result.is_ok());
    assert_eq!(queue.len(), 1, "Original queue must still have 1 entry");
}

// =========================================================================
// DIMENSION: queue-update-status-invariants
// =========================================================================

#[test]
fn rq_update_status_invalid_transition_error_details() {
    let queue = Queue::new().enqueue(QueueEntry::new("e1", "s1", 10).unwrap());
    let id = QueueEntryId::new("e1").unwrap();

    let result = queue.update_status(&id, QueueStatus::Merged);
    assert!(matches!(result, Err(ValidationError::InvalidStateTransition { .. })));
    if let Err(ValidationError::InvalidStateTransition { from, to }) = result {
        assert_eq!(from, "pending");
        assert_eq!(to, "merged");
    }
}

#[test]
fn rq_update_status_full_chain() {
    let queue = Queue::new().enqueue(QueueEntry::new("e1", "s1", 10).unwrap());
    let id = QueueEntryId::new("e1").unwrap();

    let chain = [
        QueueStatus::Claimed,
        QueueStatus::Rebasing,
        QueueStatus::Testing,
        QueueStatus::ReadyToMerge,
        QueueStatus::Merging,
        QueueStatus::Merged,
    ];

    let mut queue = queue;
    for status in &chain {
        queue = queue.update_status(&id, *status).unwrap();
    }
    assert_eq!(queue.find(&id).unwrap().status, QueueStatus::Merged);
}

#[test]
fn rq_update_status_failure_then_retry_cycle() {
    let queue = Queue::new().enqueue(QueueEntry::new("e1", "s1", 10).unwrap());
    let id = QueueEntryId::new("e1").unwrap();

    // Fail -> Retry -> Fail -> Retry -> Succeed
    let queue = queue.update_status(&id, QueueStatus::Claimed).unwrap();
    let queue = queue.update_status(&id, QueueStatus::Rebasing).unwrap();
    let queue = queue.update_status(&id, QueueStatus::Testing).unwrap();
    let queue = queue.update_status(&id, QueueStatus::FailedRetryable).unwrap();
    let queue = queue.update_status(&id, QueueStatus::Pending).unwrap();
    let queue = queue.update_status(&id, QueueStatus::Claimed).unwrap();
    let queue = queue.update_status(&id, QueueStatus::Rebasing).unwrap();
    let queue = queue.update_status(&id, QueueStatus::Testing).unwrap();
    let queue = queue.update_status(&id, QueueStatus::ReadyToMerge).unwrap();

    assert_eq!(queue.find(&id).unwrap().status, QueueStatus::ReadyToMerge);
}

// =========================================================================
// DIMENSION: queue-entry-transition-invariants
// =========================================================================

#[test]
fn rq_entry_transition_chain_preserves_id() {
    let entry = QueueEntry::new("preserve-id", "s1", 10).unwrap();
    let result = entry
        .transition_status(QueueStatus::Claimed)
        .and_then(|e| e.transition_status(QueueStatus::Rebasing))
        .and_then(|e| e.transition_status(QueueStatus::Testing))
        .and_then(|e| e.transition_status(QueueStatus::ReadyToMerge))
        .and_then(|e| e.transition_status(QueueStatus::Merging))
        .and_then(|e| e.transition_status(QueueStatus::Merged));

    assert_eq!(result.unwrap().id.as_str(), "preserve-id");
}

#[test]
fn rq_entry_transition_chain_preserves_session() {
    let entry = QueueEntry::new("id", "preserve-session", 10).unwrap();
    let result = entry
        .transition_status(QueueStatus::Claimed)
        .and_then(|e| e.transition_status(QueueStatus::Rebasing))
        .and_then(|e| e.transition_status(QueueStatus::Testing))
        .and_then(|e| e.transition_status(QueueStatus::ReadyToMerge));

    assert_eq!(result.unwrap().session.as_str(), "preserve-session");
}

#[test]
fn rq_entry_transition_chain_preserves_priority() {
    let entry = QueueEntry::new("id", "s", 42).unwrap();
    let result = entry
        .transition_status(QueueStatus::Claimed)
        .and_then(|e| e.transition_status(QueueStatus::Rebasing))
        .and_then(|e| e.transition_status(QueueStatus::Testing));

    assert_eq!(result.unwrap().priority, 42);
}

#[test]
fn rq_entry_transition_invalid_returns_error() {
    let entry = QueueEntry::new("id", "s", 10).unwrap();
    let result = entry.transition_status(QueueStatus::Merged);
    assert!(result.is_err());
    assert!(matches!(result, Err(ValidationError::InvalidStateTransition { .. })));
}

#[test]
fn rq_entry_with_priority_then_transition() {
    let entry = QueueEntry::new("id", "s", 10).unwrap();
    let updated = entry.with_priority(50).unwrap();
    let claimed = updated.transition_status(QueueStatus::Claimed).unwrap();
    assert_eq!(claimed.priority, 50);
    assert_eq!(claimed.status, QueueStatus::Claimed);
}

// =========================================================================
// DIMENSION: queue-group-by-and-filter
// =========================================================================

#[test]
fn rq_group_by_status_no_overlap() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("a", "s-a", 10).unwrap())
        .enqueue(
            QueueEntry::new("b", "s-b", 20)
                .unwrap()
                .transition_status(QueueStatus::Claimed)
                .unwrap(),
        )
        .enqueue(
            QueueEntry::new("c", "s-c", 30)
                .unwrap()
                .transition_status(QueueStatus::Claimed)
                .unwrap()
                .transition_status(QueueStatus::Rebasing)
                .unwrap()
                .transition_status(QueueStatus::Testing)
                .unwrap()
                .transition_status(QueueStatus::ReadyToMerge)
                .unwrap()
                .transition_status(QueueStatus::Merging)
                .unwrap()
                .transition_status(QueueStatus::Merged)
                .unwrap(),
        )
        .enqueue(
            QueueEntry::new("d", "s-d", 40)
                .unwrap()
                .transition_status(QueueStatus::Cancelled)
                .unwrap(),
        );

    let grouped = queue.group_by_status();
    let total: usize = grouped.iter().map(|(_, entries)| entries.len()).sum();
    assert_eq!(total, queue.len());
}

#[test]
fn rq_partition_completeness() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("a", "s-a", 10).unwrap())
        .enqueue(
            QueueEntry::new("b", "s-b", 20)
                .unwrap()
                .transition_status(QueueStatus::Claimed)
                .unwrap(),
        );

    let (yes, no) = queue.partition(|e| e.status == QueueStatus::Pending);
    assert_eq!(yes.len() + no.len(), queue.len());
}

#[test]
fn rq_sorted_by_key_does_not_mutate_original() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("c", "s-c", 30).unwrap())
        .enqueue(QueueEntry::new("a", "s-a", 10).unwrap())
        .enqueue(QueueEntry::new("b", "s-b", 20).unwrap());

    // enqueue maintains priority order: a(10), b(20), c(30)
    assert_eq!(queue.entries()[0].id.as_str(), "a");
    assert_eq!(queue.entries()[1].id.as_str(), "b");
    assert_eq!(queue.entries()[2].id.as_str(), "c");

    let _sorted = queue.sorted_by_key(|e| e.priority);

    // sorted_by_key should NOT mutate the original
    assert_eq!(queue.entries()[0].id.as_str(), "a");
    assert_eq!(queue.entries()[1].id.as_str(), "b");
    assert_eq!(queue.entries()[2].id.as_str(), "c");
}

// =========================================================================
// DIMENSION: queue-error-types
// =========================================================================

#[test]
fn rq_validation_error_all_variants_display() {
    let errors: Vec<ValidationError> = vec![
        ValidationError::EmptyValue("field".into()),
        ValidationError::InvalidCharacters { field: "f".into(), found: "c".into() },
        ValidationError::ExceedsMaximum { field: "f".into(), value: 5, max: 3 },
        ValidationError::BelowMinimum { field: "f".into(), value: 1, min: 5 },
        ValidationError::InvalidStateTransition { from: "A".into(), to: "B".into() },
        ValidationError::NotFound { field: "f".into(), value: "v".into() },
        ValidationError::AlreadyExists { field: "f".into(), value: "v".into() },
        ValidationError::OutOfBounds { position: 5, length: 3 },
        ValidationError::Multiple(vec![
            ValidationError::EmptyValue("x".into()),
            ValidationError::EmptyValue("y".into()),
        ]),
    ];

    for err in &errors {
        let display = format!("{err}");
        assert!(!display.is_empty(), "Error display should not be empty");
        let debug = format!("{err:?}");
        assert!(!debug.is_empty(), "Error debug should not be empty");
    }
}

#[test]
fn rq_validation_error_multiple_with_many_errors() {
    let errors: Vec<ValidationError> = (0..100)
        .map(|i| ValidationError::EmptyValue(format!("err-{}", i)))
        .collect();
    let multi = ValidationError::Multiple(errors);
    let display = format!("{multi}");
    assert!(display.contains("100 error(s)"));
}

// =========================================================================
// DIMENSION: queue-serde-edge-cases
// =========================================================================

#[test]
fn rq_queue_entry_serde_with_all_statuses() {
    use chrono::Utc;

    let all_statuses = [
        QueueStatus::Pending,
        QueueStatus::Claimed,
        QueueStatus::Rebasing,
        QueueStatus::Testing,
        QueueStatus::ReadyToMerge,
        QueueStatus::Merging,
        QueueStatus::Merged,
        QueueStatus::FailedRetryable,
        QueueStatus::FailedTerminal,
        QueueStatus::Cancelled,
    ];

    for status in &all_statuses {
        let entry = QueueEntry::with_status(
            QueueEntryId::new("serde-id").unwrap(),
            SessionName::new("serde-session").unwrap(),
            42,
            Utc::now(),
            *status,
        )
        .unwrap();
        let json = serde_json::to_string(&entry).unwrap();
        let back: QueueEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(back.status, *status, "Serde roundtrip failed for {:?}", status);
    }
}

#[test]
fn rq_queue_serde_large_queue() {
    let mut queue = Queue::new();
    for i in 0..200 {
        queue = queue.enqueue(QueueEntry::new(format!("e-{}", i), format!("s-{}", i), (i % 50) as u32).unwrap());
    }
    let json = serde_json::to_string(&queue).unwrap();
    let back: Queue = serde_json::from_str(&json).unwrap();
    assert_eq!(back.len(), queue.len());
}

// =========================================================================
// DIMENSION: queue-with-entry-boundaries
// =========================================================================

#[test]
fn rq_with_entry_at_position_zero_empty_queue() {
    let queue = Queue::new();
    let entry = QueueEntry::new("e1", "s1", 10).unwrap();
    let result = queue.with_entry(0, entry);
    assert!(result.is_ok());
    assert_eq!(result.unwrap().len(), 1);
}

#[test]
fn rq_with_entry_at_position_equal_to_len() {
    let queue = Queue::new().enqueue(QueueEntry::new("e1", "s1", 10).unwrap());
    let new_entry = QueueEntry::new("e2", "s2", 20).unwrap();
    // position == len is valid (insert at end)
    let result = queue.with_entry(1, new_entry);
    assert!(result.is_ok());
    assert_eq!(result.unwrap().len(), 2);
}

#[test]
fn rq_with_entry_position_beyond_len_rejected() {
    let queue = Queue::new().enqueue(QueueEntry::new("e1", "s1", 10).unwrap());
    let new_entry = QueueEntry::new("e2", "s2", 20).unwrap();
    let result = queue.with_entry(2, new_entry);
    assert!(matches!(result, Err(ValidationError::OutOfBounds { .. })));
}

#[test]
fn rq_remove_at_empty_queue_rejected() {
    let queue = Queue::new();
    let result = queue.remove_at(0);
    assert!(matches!(result, Err(ValidationError::OutOfBounds { .. })));
}

// =========================================================================
// DIMENSION: queue-next-pending-priority
// =========================================================================

#[test]
fn rq_next_pending_returns_lowest_priority_pending() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("high", "s-high", 50).unwrap())
        .enqueue(QueueEntry::new("low", "s-low", 10).unwrap())
        .enqueue(QueueEntry::new("mid", "s-mid", 30).unwrap());

    let next = queue.next_pending();
    assert!(next.is_some());
    // First pending in priority order should be priority 10
    assert_eq!(next.unwrap().priority, 10);
}

fn make_merged_entry(id: &str, session: &str, priority: u32) -> QueueEntry {
    QueueEntry::new(id, session, priority)
        .unwrap()
        .transition_status(QueueStatus::Claimed)
        .unwrap()
        .transition_status(QueueStatus::Rebasing)
        .unwrap()
        .transition_status(QueueStatus::Testing)
        .unwrap()
        .transition_status(QueueStatus::ReadyToMerge)
        .unwrap()
        .transition_status(QueueStatus::Merging)
        .unwrap()
        .transition_status(QueueStatus::Merged)
        .unwrap()
}

#[test]
fn rq_next_pending_skips_all_non_pending() {
    let queue = Queue::new()
        .enqueue(
            QueueEntry::new("a", "s-a", 10)
                .unwrap()
                .transition_status(QueueStatus::Claimed)
                .unwrap(),
        )
        .enqueue(make_merged_entry("b", "s-b", 20))
        .enqueue(
            QueueEntry::new("c", "s-c", 30)
                .unwrap()
                .transition_status(QueueStatus::Cancelled)
                .unwrap(),
        );

    assert!(queue.next_pending().is_none());
}

#[test]
fn rq_next_pending_after_dequeue_of_first_pending() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("first", "s-first", 10).unwrap())
        .enqueue(QueueEntry::new("second", "s-second", 20).unwrap());

    let id = QueueEntryId::new("first").unwrap();
    let (queue, _) = queue.dequeue(&id);

    let next = queue.next_pending();
    assert!(next.is_some());
    assert_eq!(next.unwrap().id.as_str(), "second");
}

// =========================================================================
// DIMENSION: queue-find-by-session
// =========================================================================

#[test]
fn rq_find_by_session_returns_first_match() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("a", "same-session", 10).unwrap())
        .enqueue(QueueEntry::new("b", "same-session", 20).unwrap());

    let session = SessionName::new("same-session").unwrap();
    let found = queue.find_by_session(&session);
    assert!(found.is_some());
    // Should return the first match (lowest priority = 10)
    assert_eq!(found.unwrap().priority, 10);
}

#[test]
fn rq_find_by_session_case_sensitive() {
    let queue = Queue::new().enqueue(QueueEntry::new("a", "MySession", 10).unwrap());
    let session = SessionName::new("mysession").unwrap();
    assert!(queue.find_by_session(&session).is_none());
}

// =========================================================================
// DIMENSION: queue-serde-status-pascal-case
// =========================================================================

#[test]
fn rq_queue_status_serde_uses_pascal_case() {
    let statuses = [
        (QueueStatus::Pending, "\"Pending\""),
        (QueueStatus::Claimed, "\"Claimed\""),
        (QueueStatus::Rebasing, "\"Rebasing\""),
        (QueueStatus::Testing, "\"Testing\""),
        (QueueStatus::ReadyToMerge, "\"ReadyToMerge\""),
        (QueueStatus::Merging, "\"Merging\""),
        (QueueStatus::Merged, "\"Merged\""),
        (QueueStatus::FailedRetryable, "\"FailedRetryable\""),
        (QueueStatus::FailedTerminal, "\"FailedTerminal\""),
        (QueueStatus::Cancelled, "\"Cancelled\""),
    ];

    for (status, expected_json) in &statuses {
        let json = serde_json::to_string(status).unwrap();
        assert_eq!(&json, expected_json, "Serde JSON mismatch for {:?}", status);
    }
}

// =========================================================================
// DIMENSION: queue-status-display-snake-case
// =========================================================================

#[test]
fn rq_queue_status_display_uses_snake_case() {
    let display = format!("{}", QueueStatus::ReadyToMerge);
    assert_eq!(display, "ready_to_merge");

    let display = format!("{}", QueueStatus::FailedRetryable);
    assert_eq!(display, "failed_retryable");

    let display = format!("{}", QueueStatus::FailedTerminal);
    assert_eq!(display, "failed_terminal");
}

// =========================================================================
// DIMENSION: queue-from-entries-sorted
// =========================================================================

#[test]
fn rq_from_entries_sorted_empty() {
    let queue = Queue::from_entries_sorted(vec![]);
    assert!(queue.is_empty());
}

#[test]
fn rq_from_entries_sorted_single() {
    let entries = vec![QueueEntry::new("e1", "s1", 50).unwrap()];
    let queue = Queue::from_entries_sorted(entries);
    assert_eq!(queue.len(), 1);
}

#[test]
fn rq_from_entries_sorted_reverse_order() {
    let entries = vec![
        QueueEntry::new("c", "s-c", 30).unwrap(),
        QueueEntry::new("b", "s-b", 20).unwrap(),
        QueueEntry::new("a", "s-a", 10).unwrap(),
    ];
    let queue = Queue::from_entries_sorted(entries);
    let priorities: Vec<u32> = queue.entries().iter().map(|e| e.priority).collect();
    assert_eq!(priorities, vec![10, 20, 30]);
}

#[test]
fn rq_from_entries_sorted_duplicate_priorities() {
    let entries = vec![
        QueueEntry::new("c", "s-c", 10).unwrap(),
        QueueEntry::new("b", "s-b", 10).unwrap(),
        QueueEntry::new("a", "s-a", 10).unwrap(),
    ];
    let queue = Queue::from_entries_sorted(entries);
    assert_eq!(queue.len(), 3);
    // All same priority, just verify no panic
    for e in queue.entries() {
        assert_eq!(e.priority, 10);
    }
}

// =========================================================================
// DIMENSION: queue-into-inner
// =========================================================================

#[test]
fn rq_into_inner_preserves_all_entries() {
    let queue = Queue::new()
        .enqueue(QueueEntry::new("a", "s-a", 10).unwrap())
        .enqueue(QueueEntry::new("b", "s-b", 20).unwrap());

    let entries = queue.into_inner();
    assert_eq!(entries.len(), 2);
    assert_eq!(entries[0].id.as_str(), "a");
    assert_eq!(entries[1].id.as_str(), "b");
}

#[test]
fn rq_into_inner_empty() {
    let queue = Queue::new();
    let entries = queue.into_inner();
    assert!(entries.is_empty());
}

// =========================================================================
// DIMENSION: proptest-state-machine-exhaustive
// =========================================================================

mod proptest_red_queen {
    use super::*;
    use proptest::prelude::*;

    proptest! {
        #[test]
        fn prop_rq_transition_result_matches_exhaustive_map(
            from_idx in 0u8..10u8,
            to_idx in 0u8..10u8
        ) {
            let all = [
                QueueStatus::Pending,
                QueueStatus::Claimed,
                QueueStatus::Rebasing,
                QueueStatus::Testing,
                QueueStatus::ReadyToMerge,
                QueueStatus::Merging,
                QueueStatus::Merged,
                QueueStatus::FailedRetryable,
                QueueStatus::FailedTerminal,
                QueueStatus::Cancelled,
            ];
            let from = all[from_idx as usize];
            let to = all[to_idx as usize];

            let result = from.transition_to(to);
            match result {
                Ok(status) => prop_assert_eq!(status, to),
                Err(_) => prop_assert!(true),
            }
        }

        #[test]
        fn prop_rq_immutability_after_any_operation(
            ops in proptest::collection::vec(
                proptest::prop_oneof![
                    proptest::strategy::Just(0u8), // enqueue
                    proptest::strategy::Just(1u8), // dequeue
                ],
                1..20
            ),
        ) {
            let mut queue = Queue::new();
            let mut counter = 0u64;

            for op in &ops {
                match op {
                    0 => {
                        let id = format!("e-{}", counter);
                        let sess = format!("s-{}", counter);
                        counter += 1;
                        if let Ok(entry) = QueueEntry::new(&id, &sess, (counter % 100) as u32) {
                            queue = queue.enqueue(entry);
                        }
                    }
                    1 => {
                        if !queue.is_empty() {
                            if let Some(first) = queue.entries().first() {
                                let id = first.id.clone();
                                let (q, _) = queue.dequeue(&id);
                                queue = q;
                            }
                        }
                    }
                    _ => unreachable!(),
                }

                let len = queue.len();
                prop_assert_eq!(len, queue.entries().len());
            }
        }

        #[test]
        fn prop_rq_priority_ordering_always_sorted(
            entries in proptest::collection::vec(
                (
                    "[a-zA-Z0-9_-]{1,20}",
                    "[a-zA-Z0-9_-]{1,20}",
                    0..=MAX_PRIORITY
                ),
                0..100
            )
        ) {
            let mut queue = Queue::new();
            for (id, session, priority) in &entries {
                if let Ok(entry) = QueueEntry::new(id, session, *priority) {
                    queue = queue.enqueue(entry);
                }
            }

            let priorities: Vec<u32> = queue.entries().iter().map(|e| e.priority).collect();
            for window in priorities.windows(2) {
                prop_assert!(window[0] <= window[1], "Not sorted: {:?} > {:?}", window[0], window[1]);
            }
        }

        #[test]
        fn prop_rq_entry_serde_roundtrip_preserves_all_fields(
            id in "[a-zA-Z0-9_-]{1,20}",
            session in "[a-zA-Z0-9_.-]{1,20}",
            priority in 0..=MAX_PRIORITY,
            status_idx in 0u8..10u8
        ) {
            let all_statuses = [
                QueueStatus::Pending,
                QueueStatus::Claimed,
                QueueStatus::Rebasing,
                QueueStatus::Testing,
                QueueStatus::ReadyToMerge,
                QueueStatus::Merging,
                QueueStatus::Merged,
                QueueStatus::FailedRetryable,
                QueueStatus::FailedTerminal,
                QueueStatus::Cancelled,
            ];

            if let Ok(entry) = QueueEntry::new(&id, &session, priority) {
                let target_status = all_statuses[status_idx as usize];

                let chain = match target_status {
                    QueueStatus::Pending => vec![QueueStatus::Pending],
                    QueueStatus::Claimed => vec![QueueStatus::Claimed],
                    QueueStatus::Rebasing => vec![QueueStatus::Claimed, QueueStatus::Rebasing],
                    QueueStatus::Testing => vec![QueueStatus::Claimed, QueueStatus::Rebasing, QueueStatus::Testing],
                    QueueStatus::ReadyToMerge => vec![QueueStatus::Claimed, QueueStatus::Rebasing, QueueStatus::Testing, QueueStatus::ReadyToMerge],
                    QueueStatus::Merging => vec![QueueStatus::Claimed, QueueStatus::Rebasing, QueueStatus::Testing, QueueStatus::ReadyToMerge, QueueStatus::Merging],
                    QueueStatus::Merged => vec![QueueStatus::Claimed, QueueStatus::Rebasing, QueueStatus::Testing, QueueStatus::ReadyToMerge, QueueStatus::Merging, QueueStatus::Merged],
                    QueueStatus::FailedRetryable => vec![QueueStatus::Claimed, QueueStatus::Rebasing, QueueStatus::Testing, QueueStatus::FailedRetryable],
                    QueueStatus::FailedTerminal => vec![QueueStatus::Claimed, QueueStatus::Rebasing, QueueStatus::Testing, QueueStatus::FailedTerminal],
                    QueueStatus::Cancelled => vec![QueueStatus::Cancelled],
                };

                let mut current = entry;
                for status in chain {
                    let result = current.transition_status(status);
                    match result {
                        Ok(e) => current = e,
                        Err(_) => return Ok(()), // Invalid chain, skip this case
                    }
                }

                let json = serde_json::to_string(&current).unwrap();
                let back: QueueEntry = serde_json::from_str(&json).unwrap();
                prop_assert_eq!(back.id.as_str(), current.id.as_str());
                prop_assert_eq!(back.session.as_str(), current.session.as_str());
                prop_assert_eq!(back.priority, current.priority);
                prop_assert_eq!(back.status, current.status);
            }
        }

        #[test]
        fn prop_rq_queue_len_after_interleaved_ops(
            ops in proptest::collection::vec(
                proptest::prop_oneof![
                    proptest::strategy::Just(0u8), // enqueue
                    proptest::strategy::Just(1u8), // dequeue
                    proptest::strategy::Just(2u8), // remove_at 0
                ],
                1..50
            )
        ) {
            let mut queue = Queue::new();
            let mut counter: u32 = 0;

            for op in &ops {
                match op {
                    0 => {
                        let id = format!("e-{}", counter);
                        let sess = format!("s-{}", counter);
                        counter += 1;
                        if let Ok(entry) = QueueEntry::new(&id, &sess, counter % 100) {
                            queue = queue.enqueue(entry);
                        }
                    }
                    1 => {
                        if !queue.is_empty() {
                            if let Some(first) = queue.entries().first() {
                                let id = first.id.clone();
                                let (q, _) = queue.dequeue(&id);
                                queue = q;
                            }
                        }
                    }
                    2 => {
                        if !queue.is_empty() {
                            let (q, _) = queue.remove_at(0).unwrap();
                            queue = q;
                        }
                    }
                    _ => unreachable!(),
                }
                prop_assert_eq!(queue.len(), queue.entries().len());
            }
        }

        #[test]
        fn prop_rq_validator_collects_correct_error_count(
            errors in proptest::collection::vec(
                proptest::collection::vec("[a-z]{1,5}", 1..5),
                0..10
            )
        ) {
            let mut v = Validator::new();
            let mut expected_count = 0usize;

            for group in &errors {
                if group.is_empty() {
                    continue;
                }
                for name in group {
                    v.add_error(ValidationError::EmptyValue(name.clone()));
                    expected_count += 1;
                }
            }

            prop_assert_eq!(v.error_count(), expected_count);

            let result = v.finalize();
            if expected_count == 0 {
                prop_assert!(result.is_ok());
            } else if expected_count == 1 {
                prop_assert!(result.is_err());
                prop_assert!(!matches!(result, Err(ValidationError::Multiple(_))));
            } else {
                prop_assert!(matches!(result, Err(ValidationError::Multiple(_))));
                if let Err(ValidationError::Multiple(errs)) = result {
                    prop_assert_eq!(errs.len(), expected_count);
                }
            }
        }
    }
}
