[package]
name = "scp-stack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gix = { workspace = true }
octocrab = { workspace = true }
tokio.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
petgraph.workspace = true
chrono.workspace = true

[dev-dependencies]
insta.workspace = true
proptest.workspace = true
tempfile.workspace = true
