//! Red Queen Evolution — Adversarial co-evolving test suite for scp-isolate.
//!
//! Generated by deterministic adversarial evolution protocol.
//! These tests target mutation-surviving code paths, missing invariants,
//! and edge cases not covered by the existing 140-test suite.
//!
//! Dimensions:
//! - state-machine-exhaustive: Every transition pair validated
//! - guard-invariants: RAII lifecycle edge cases
//! - event-exhaustiveness: All 17 event variants exercised
//! - dag-adversarial: Cycle detection, diamond patterns, removal order
//! - checkpoint-risk: Classification boundary conditions
//! - hint-generation: State-driven hint coverage gaps
//! - type-invariants: ID validation, serialization, equality

#![deny(clippy::unwrap_used)]
#![deny(clippy::expect_used)]
#![deny(clippy::panic)]
#![forbid(unsafe_code)]

use scp_isolate::dag::{BranchDag, BranchId, DagError};
use scp_isolate::{
    classify_command, BeadId, BeadWorkspaceMapping, CheckpointRecord, CheckpointState,
    EventContext, EventType, IsolateEvent, OperationRisk, WorkspaceGuard, WorkspaceId,
    WorkspaceState, WorkspaceStateMachine,
};

// =========================================================================
// DIMENSION: state-machine-exhaustive
// =========================================================================

#[test]
fn rq_state_machine_all_pairs_classified() {
    let all = WorkspaceState::all();
    for from in all {
        for to in all {
            let result = WorkspaceStateMachine::transition(*from, *to);
            let valid = from.can_transition_to(*to);
            assert_eq!(
                result.is_ok(),
                valid,
                "Inconsistency: transition({from:?}, {to:?}) = {:?}, can_transition = {valid}",
                result.map(|_| "ok"),
            );
        }
    }
}

#[test]
fn rq_state_machine_self_transitions_all_rejected() {
    for state in WorkspaceState::all() {
        let result = WorkspaceStateMachine::transition(*state, *state);
        assert!(
            result.is_err(),
            "Self-transition {:?} -> {:?} should be rejected",
            state,
            state
        );
    }
}

#[test]
fn rq_state_machine_created_direct_to_terminal_rejected() {
    let terminals = [WorkspaceState::Merged, WorkspaceState::Abandoned];
    for target in &terminals {
        let result = WorkspaceStateMachine::transition(WorkspaceState::Created, *target);
        assert!(
            result.is_err(),
            "Created -> {target:?} should be rejected (must go through Working)"
        );
    }
}

#[test]
fn rq_state_machine_created_direct_to_ready_or_conflict_rejected() {
    let skipped = [WorkspaceState::Ready, WorkspaceState::Conflict];
    for target in &skipped {
        let result = WorkspaceStateMachine::transition(WorkspaceState::Created, *target);
        assert!(
            result.is_err(),
            "Created -> {target:?} should be rejected (must go through Working)"
        );
    }
}

#[test]
fn rq_state_machine_working_to_merged_rejected() {
    let result = WorkspaceStateMachine::transition(WorkspaceState::Working, WorkspaceState::Merged);
    assert!(
        result.is_err(),
        "Working -> Merged should be rejected (must go through Ready)"
    );
}

#[test]
fn rq_state_machine_ready_cannot_go_back_to_created() {
    let result = WorkspaceStateMachine::transition(WorkspaceState::Ready, WorkspaceState::Created);
    assert!(
        result.is_err(),
        "Ready -> Created should be rejected (no going back)"
    );
}

#[test]
fn rq_state_machine_conflict_to_ready_rejected() {
    let result = WorkspaceStateMachine::transition(WorkspaceState::Conflict, WorkspaceState::Ready);
    assert!(
        result.is_err(),
        "Conflict -> Ready should be rejected (must go through Working)"
    );
}

#[test]
fn rq_state_machine_abandoned_to_any_rejected_exhaustive() {
    for target in WorkspaceState::all() {
        let result = WorkspaceStateMachine::transition(WorkspaceState::Abandoned, *target);
        assert!(
            result.is_err(),
            "Abandoned -> {target:?} should always be rejected"
        );
    }
}

#[test]
fn rq_state_machine_merged_to_any_rejected_exhaustive() {
    for target in WorkspaceState::all() {
        let result = WorkspaceStateMachine::transition(WorkspaceState::Merged, *target);
        assert!(
            result.is_err(),
            "Merged -> {target:?} should always be rejected"
        );
    }
}

#[test]
fn rq_state_machine_valid_next_states_match_can_transition() {
    for state in WorkspaceState::all() {
        for next in state.valid_next_states() {
            assert!(
                state.can_transition_to(*next),
                "valid_next_states({state:?}) contains {next:?} but can_transition_to returns false"
            );
        }
    }
}

#[test]
fn rq_state_machine_no_surprise_valid_transitions() {
    // Every transition that can_transition says yes should also be in valid_next_states
    for from in WorkspaceState::all() {
        for to in WorkspaceState::all() {
            if from.can_transition_to(*to) {
                assert!(
                    from.valid_next_states().contains(to),
                    "can_transition({from:?}, {to:?}) is true but not in valid_next_states"
                );
            }
        }
    }
}

#[test]
fn rq_state_machine_is_active_is_complete_are_mutually_exclusive_for_terminals() {
    for state in WorkspaceState::all() {
        if state.is_terminal() {
            assert!(
                !state.is_active(),
                "Terminal state {state:?} should not be active"
            );
        }
    }
}

#[test]
fn rq_state_machine_recovery_cycle_conflict_working_conflict() {
    let s = WorkspaceState::Created;
    let s = WorkspaceStateMachine::transition(s, WorkspaceState::Working).unwrap();
    let s = WorkspaceStateMachine::transition(s, WorkspaceState::Conflict).unwrap();
    let s = WorkspaceStateMachine::transition(s, WorkspaceState::Working).unwrap();
    // Can go back to Conflict from Working
    let s = WorkspaceStateMachine::transition(s, WorkspaceState::Conflict).unwrap();
    assert!(s.is_active());
    assert!(!s.is_terminal());
}

#[test]
fn rq_state_machine_ready_to_abandoned() {
    let s = WorkspaceState::Created;
    let s = WorkspaceStateMachine::transition(s, WorkspaceState::Working).unwrap();
    let s = WorkspaceStateMachine::transition(s, WorkspaceState::Ready).unwrap();
    let s = WorkspaceStateMachine::transition(s, WorkspaceState::Abandoned).unwrap();
    assert!(s.is_terminal());
}

// =========================================================================
// DIMENSION: guard-invariants
// =========================================================================

fn test_ws_id() -> WorkspaceId {
    WorkspaceId::generate()
}

fn test_bead_id() -> BeadId {
    BeadId::parse("rq-bead".into()).unwrap()
}

#[test]
fn rq_guard_double_commit_fails() {
    let guard =
        WorkspaceGuard::acquire(test_ws_id(), test_bead_id(), WorkspaceState::Created).unwrap();
    let _committed = guard.commit().unwrap();
    // guard is consumed — cannot commit again (move semantics)
    // This test verifies the type system prevents double-use
}

#[test]
fn rq_guard_commit_then_abandon_type_safe() {
    let guard =
        WorkspaceGuard::acquire(test_ws_id(), test_bead_id(), WorkspaceState::Created).unwrap();
    let committed = guard.commit().unwrap();
    assert!(committed.is_ready());
    assert!(!committed.is_abandoned());
    // CommittedGuard has no commit/abandon methods — verified by type system
}

#[test]
fn rq_guard_all_non_created_states_rejected() {
    let non_created = [
        WorkspaceState::Working,
        WorkspaceState::Ready,
        WorkspaceState::Merged,
        WorkspaceState::Abandoned,
        WorkspaceState::Conflict,
    ];
    for state in &non_created {
        let result = WorkspaceGuard::acquire(test_ws_id(), test_bead_id(), *state);
        assert!(result.is_err(), "acquire with {state:?} should fail");
    }
}

#[test]
fn rq_guard_mapping_bead_matches() {
    let ws_id = WorkspaceId::parse("ws-rq-1".into()).unwrap();
    let bead_id = BeadId::parse("bead-rq-1".into()).unwrap();
    let guard =
        WorkspaceGuard::acquire(ws_id.clone(), bead_id.clone(), WorkspaceState::Created).unwrap();
    let mapping = guard.mapping().unwrap();
    assert_eq!(mapping.bead_id(), &bead_id);
    assert_eq!(mapping.workspace_id(), &ws_id);
}

#[test]
fn rq_guard_workspace_id_generate_format() {
    let id = WorkspaceId::generate();
    let s = id.as_str();
    assert!(s.starts_with("iso-"));
    // Format: iso-{timestamp}-{counter}
    let parts: Vec<&str> = s.split('-').collect();
    assert!(parts.len() >= 3, "expected at least 3 parts in '{s}'");
}

#[test]
fn rq_committed_guard_round_trip_commit() {
    let ws_id = test_ws_id();
    let bead_id = test_bead_id();
    let guard =
        WorkspaceGuard::acquire(ws_id.clone(), bead_id.clone(), WorkspaceState::Created).unwrap();
    let committed = guard.commit().unwrap();
    let cloned = committed.clone();
    assert_eq!(committed.workspace_id(), cloned.workspace_id());
    assert_eq!(committed.bead_id(), cloned.bead_id());
    assert_eq!(committed.state(), cloned.state());
}

#[test]
fn rq_committed_guard_round_trip_abandon() {
    let ws_id = test_ws_id();
    let bead_id = test_bead_id();
    let guard =
        WorkspaceGuard::acquire(ws_id.clone(), bead_id.clone(), WorkspaceState::Created).unwrap();
    let committed = guard.abandon().unwrap();
    assert!(committed.is_abandoned());
    assert!(!committed.is_ready());
    assert!(committed.state().is_terminal());
}

#[test]
fn rq_bead_workspace_mapping_timestamp_reasonable() {
    let before = chrono::Utc::now();
    let mapping = BeadWorkspaceMapping::new(
        BeadId::parse("b".into()).unwrap(),
        WorkspaceId::parse("w".into()).unwrap(),
    );
    let after = chrono::Utc::now();
    assert!(mapping.assigned_at() >= before);
    assert!(mapping.assigned_at() <= after);
}

// =========================================================================
// DIMENSION: event-exhaustiveness
// =========================================================================

fn rq_ctx(name: &str) -> EventContext {
    EventContext::for_workspace(name.to_string())
}

fn rq_now() -> chrono::DateTime<chrono::Utc> {
    chrono::Utc::now()
}

#[test]
fn rq_event_all_variants_have_distinct_names() {
    let events: Vec<(&str, IsolateEvent)> = vec![
        (
            "workspace.created",
            IsolateEvent::WorkspaceCreated {
                name: "w".into(),
                source: "s".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "workspace.activated",
            IsolateEvent::WorkspaceActivated {
                name: "w".into(),
                state: WorkspaceState::Working,
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "workspace.syncing",
            IsolateEvent::WorkspaceSyncing {
                name: "w".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "workspace.synced",
            IsolateEvent::WorkspaceSynced {
                name: "w".into(),
                commits_rebased: 0,
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "workspace.paused",
            IsolateEvent::WorkspacePaused {
                name: "w".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "workspace.resumed",
            IsolateEvent::WorkspaceResumed {
                name: "w".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "workspace.completed",
            IsolateEvent::WorkspaceCompleted {
                name: "w".into(),
                branch: "b".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "workspace.failed",
            IsolateEvent::WorkspaceFailed {
                name: "w".into(),
                reason: "r".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "session.started",
            IsolateEvent::SessionStarted {
                name: "w".into(),
                session_id: "s".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "session.ended",
            IsolateEvent::SessionEnded {
                name: "w".into(),
                session_id: "s".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "agent.claimed",
            IsolateEvent::AgentClaimed {
                name: "w".into(),
                agent_id: "a".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "agent.released",
            IsolateEvent::AgentReleased {
                name: "w".into(),
                agent_id: "a".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "vcs.branch_created",
            IsolateEvent::BranchCreated {
                name: "w".into(),
                branch: "b".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "vcs.branch_pushed",
            IsolateEvent::BranchPushed {
                name: "w".into(),
                branch: "b".into(),
                commits: 0,
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "vcs.rebase_completed",
            IsolateEvent::RebaseCompleted {
                name: "w".into(),
                commits: 0,
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "vcs.conflict_detected",
            IsolateEvent::ConflictDetected {
                name: "w".into(),
                files: vec![],
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
        (
            "vcs.conflict_resolved",
            IsolateEvent::ConflictResolved {
                name: "w".into(),
                context: rq_ctx("w"),
                timestamp: rq_now(),
            },
        ),
    ];

    // 17 distinct event variants
    assert_eq!(events.len(), 17, "expected 17 event variants");

    // All names are unique
    let mut names: Vec<&str> = events.iter().map(|(n, _)| *n).collect();
    names.sort();
    let deduped: std::collections::HashSet<&str> = names.iter().copied().collect();
    assert_eq!(names.len(), deduped.len(), "event names should be unique");
}

#[test]
fn rq_event_workspace_accessor_always_returns_input() {
    let names = [
        "ws-alpha",
        "ws-beta",
        "ws-123",
        "a",
        "workspace-with-dashes",
    ];
    for name in &names {
        let e = IsolateEvent::WorkspaceCreated {
            name: name.to_string(),
            source: "test".into(),
            context: rq_ctx(name),
            timestamp: rq_now(),
        };
        assert_eq!(e.workspace(), *name);
    }
}

#[test]
fn rq_event_context_chaining_full() {
    let ctx = EventContext::for_workspace("w".into()).with_session("s1".into());
    assert!(!ctx.has_agent());
    assert!(ctx.has_session());
    assert_eq!(ctx.session_id.as_deref(), Some("s1"));

    let ctx2 = EventContext::for_agent("w".into(), "a1".into()).with_session("s2".into());
    assert!(ctx2.has_agent());
    assert!(ctx2.has_session());
    assert_eq!(ctx2.agent_id.as_deref(), Some("a1"));
    assert_eq!(ctx2.session_id.as_deref(), Some("s2"));
}

#[test]
fn rq_event_serde_roundtrip_all_variants() {
    let events: Vec<IsolateEvent> = vec![
        IsolateEvent::WorkspaceCreated {
            name: "w".into(),
            source: "cli".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceActivated {
            name: "w".into(),
            state: WorkspaceState::Working,
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceSyncing {
            name: "w".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceSynced {
            name: "w".into(),
            commits_rebased: 5,
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspacePaused {
            name: "w".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceResumed {
            name: "w".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceCompleted {
            name: "w".into(),
            branch: "main".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceFailed {
            name: "w".into(),
            reason: "oom".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::SessionStarted {
            name: "w".into(),
            session_id: "sess".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::SessionEnded {
            name: "w".into(),
            session_id: "sess".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::AgentClaimed {
            name: "w".into(),
            agent_id: "bot".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::AgentReleased {
            name: "w".into(),
            agent_id: "bot".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::BranchCreated {
            name: "w".into(),
            branch: "feat".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::BranchPushed {
            name: "w".into(),
            branch: "feat".into(),
            commits: 3,
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::RebaseCompleted {
            name: "w".into(),
            commits: 7,
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::ConflictDetected {
            name: "w".into(),
            files: vec!["a.rs".into(), "b.rs".into(), "c.rs".into()],
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::ConflictResolved {
            name: "w".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
    ];

    for e in &events {
        let json = serde_json::to_string(e).unwrap();
        let parsed: IsolateEvent = serde_json::from_str(&json).unwrap();
        assert_eq!(
            *e,
            parsed,
            "serde roundtrip failed for {:?}",
            e.event_name()
        );
    }
}

#[test]
fn rq_event_type_classification_completeness() {
    // Every event variant must classify into exactly one EventType
    let mut event_type_counts = std::collections::HashMap::new();
    let events: Vec<IsolateEvent> = vec![
        IsolateEvent::WorkspaceCreated {
            name: "w".into(),
            source: "s".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceActivated {
            name: "w".into(),
            state: WorkspaceState::Working,
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceSyncing {
            name: "w".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceSynced {
            name: "w".into(),
            commits_rebased: 0,
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspacePaused {
            name: "w".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceResumed {
            name: "w".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceCompleted {
            name: "w".into(),
            branch: "b".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::WorkspaceFailed {
            name: "w".into(),
            reason: "r".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::SessionStarted {
            name: "w".into(),
            session_id: "s".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::SessionEnded {
            name: "w".into(),
            session_id: "s".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::AgentClaimed {
            name: "w".into(),
            agent_id: "a".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::AgentReleased {
            name: "w".into(),
            agent_id: "a".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::BranchCreated {
            name: "w".into(),
            branch: "b".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::BranchPushed {
            name: "w".into(),
            branch: "b".into(),
            commits: 0,
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::RebaseCompleted {
            name: "w".into(),
            commits: 0,
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::ConflictDetected {
            name: "w".into(),
            files: vec![],
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
        IsolateEvent::ConflictResolved {
            name: "w".into(),
            context: rq_ctx("w"),
            timestamp: rq_now(),
        },
    ];

    for e in &events {
        let et = e.event_type();
        *event_type_counts
            .entry(format!("{:?}", et))
            .or_insert(0usize) += 1;
    }

    assert_eq!(
        *event_type_counts.get("WorkspaceLifecycle").unwrap_or(&0),
        8
    );
    assert_eq!(*event_type_counts.get("Session").unwrap_or(&0), 2);
    assert_eq!(*event_type_counts.get("Agent").unwrap_or(&0), 2);
    assert_eq!(*event_type_counts.get("Vcs").unwrap_or(&0), 5);
}

#[test]
fn rq_event_timestamp_preserved() {
    let ts = chrono::DateTime::parse_from_rfc3339("2025-01-01T00:00:00Z")
        .unwrap()
        .with_timezone(&chrono::Utc);
    let e = IsolateEvent::WorkspaceCreated {
        name: "w".into(),
        source: "s".into(),
        context: rq_ctx("w"),
        timestamp: ts,
    };
    assert_eq!(e.timestamp(), &ts);
}

// =========================================================================
// DIMENSION: dag-adversarial
// =========================================================================

#[test]
fn rq_dag_cycle_a_b_a_detected() {
    let mut dag = BranchDag::new();
    dag.add_branch(BranchId::new("a"), vec![BranchId::new("trunk")])
        .unwrap();
    dag.add_branch(BranchId::new("b"), vec![BranchId::new("a")])
        .unwrap();
    let result = dag.add_branch(BranchId::new("a"), vec![BranchId::new("b")]);
    // "a" already exists so it's BranchAlreadyExists, not CycleDetected
    assert!(result.is_err());
}

#[test]
fn rq_dag_trunk_cannot_be_added() {
    let mut dag = BranchDag::new();
    let result = dag.add_branch(BranchId::new("trunk"), vec![]);
    assert!(matches!(result, Err(DagError::BranchAlreadyExists(_))));
}

#[test]
fn rq_dag_trunk_can_be_removed_when_no_descendants() {
    let mut dag = BranchDag::new();
    let result = dag.remove_branch(BranchId::new("trunk"));
    // trunk has no descendants, so removal succeeds
    assert!(
        result.is_ok(),
        "trunk should be removable when it has no descendants"
    );
    // After removing trunk, DAG has 0 branches
    assert_eq!(dag.len(), 0);
    // is_empty() checks len == 1 (trunk only), so with 0 branches it returns false
    assert!(!dag.is_empty() || dag.len() == 0);
}

#[test]
fn rq_dag_deep_diamond_pattern() {
    let mut dag = BranchDag::new();
    // trunk -> a, b -> c -> d
    dag.add_branch(BranchId::new("a"), vec![BranchId::new("trunk")])
        .unwrap();
    dag.add_branch(BranchId::new("b"), vec![BranchId::new("trunk")])
        .unwrap();
    dag.add_branch(
        BranchId::new("c"),
        vec![BranchId::new("a"), BranchId::new("b")],
    )
    .unwrap();
    dag.add_branch(BranchId::new("d"), vec![BranchId::new("c")])
        .unwrap();

    let order = dag.topological_sort().unwrap();
    assert_eq!(order.len(), 5);

    let trunk_pos = order
        .iter()
        .position(|id| id == &BranchId::new("trunk"))
        .unwrap();
    let a_pos = order
        .iter()
        .position(|id| id == &BranchId::new("a"))
        .unwrap();
    let b_pos = order
        .iter()
        .position(|id| id == &BranchId::new("b"))
        .unwrap();
    let c_pos = order
        .iter()
        .position(|id| id == &BranchId::new("c"))
        .unwrap();
    let d_pos = order
        .iter()
        .position(|id| id == &BranchId::new("d"))
        .unwrap();

    assert!(trunk_pos < a_pos);
    assert!(trunk_pos < b_pos);
    assert!(a_pos < c_pos);
    assert!(b_pos < c_pos);
    assert!(c_pos < d_pos);
}

#[test]
fn rq_dag_ancestors_diamond() {
    let mut dag = BranchDag::new();
    dag.add_branch(BranchId::new("a"), vec![BranchId::new("trunk")])
        .unwrap();
    dag.add_branch(BranchId::new("b"), vec![BranchId::new("trunk")])
        .unwrap();
    dag.add_branch(
        BranchId::new("c"),
        vec![BranchId::new("a"), BranchId::new("b")],
    )
    .unwrap();

    let ancestors = dag.ancestors(&BranchId::new("c")).unwrap();
    assert_eq!(ancestors.len(), 3); // trunk, a, b
    assert!(ancestors.contains(&BranchId::new("trunk")));
    assert!(ancestors.contains(&BranchId::new("a")));
    assert!(ancestors.contains(&BranchId::new("b")));
}

#[test]
fn rq_dag_descendants_diamond() {
    let mut dag = BranchDag::new();
    dag.add_branch(BranchId::new("a"), vec![BranchId::new("trunk")])
        .unwrap();
    dag.add_branch(BranchId::new("b"), vec![BranchId::new("trunk")])
        .unwrap();
    dag.add_branch(
        BranchId::new("c"),
        vec![BranchId::new("a"), BranchId::new("b")],
    )
    .unwrap();

    let desc = dag.descendants(&BranchId::new("trunk")).unwrap();
    assert_eq!(desc.len(), 3);
    assert!(desc.contains(&BranchId::new("a")));
    assert!(desc.contains(&BranchId::new("b")));
    assert!(desc.contains(&BranchId::new("c")));
}

#[test]
fn rq_dag_remove_leaf_then_parent() {
    let mut dag = BranchDag::new();
    dag.add_branch(BranchId::new("a"), vec![BranchId::new("trunk")])
        .unwrap();
    dag.add_branch(BranchId::new("b"), vec![BranchId::new("a")])
        .unwrap();

    // Remove leaf first
    dag.remove_branch(BranchId::new("b")).unwrap();
    assert!(!dag.contains(&BranchId::new("b")));

    // Now parent has no descendants, can be removed
    dag.remove_branch(BranchId::new("a")).unwrap();
    assert!(!dag.contains(&BranchId::new("a")));
    assert_eq!(dag.len(), 1);
}

#[test]
fn rq_dag_branch_ids_always_sorted() {
    let mut dag = BranchDag::new();
    let names = ["z", "m", "a", "f", "c"];
    for name in &names {
        dag.add_branch(BranchId::new(*name), vec![BranchId::new("trunk")])
            .unwrap();
    }
    let ids = dag.branch_ids();
    let mut sorted = ids.clone();
    sorted.sort();
    assert_eq!(ids, sorted, "branch_ids() must return sorted order");
}

#[test]
fn rq_dag_empty_topo_sort_fails() {
    // New DAG has trunk, so remove it first to get truly empty
    let mut dag = BranchDag::new();
    dag.remove_branch(BranchId::new("trunk")).ok();
    let result = dag.topological_sort();
    assert!(matches!(result, Err(DagError::EmptyDag)));
}

#[test]
fn rq_dag_path_to_root_diamond() {
    let mut dag = BranchDag::new();
    dag.add_branch(BranchId::new("a"), vec![BranchId::new("trunk")])
        .unwrap();
    dag.add_branch(BranchId::new("b"), vec![BranchId::new("trunk")])
        .unwrap();
    dag.add_branch(
        BranchId::new("c"),
        vec![BranchId::new("a"), BranchId::new("b")],
    )
    .unwrap();

    let path = dag.path_to_root(&BranchId::new("c")).unwrap();
    assert_eq!(path[0], BranchId::new("c"));
    // First parent in the list determines the path
    assert!(path.contains(&BranchId::new("a")));
    assert!(path.contains(&BranchId::new("trunk")));
    assert!(path.last().unwrap() == &BranchId::new("trunk"));
}

#[test]
fn rq_dag_wide_fan_out() {
    let mut dag = BranchDag::new();
    for i in 0..20 {
        dag.add_branch(
            BranchId::new(format!("branch-{i}")),
            vec![BranchId::new("trunk")],
        )
        .unwrap();
    }
    assert_eq!(dag.len(), 21);
    let desc = dag.descendants(&BranchId::new("trunk")).unwrap();
    assert_eq!(desc.len(), 20);
}

#[test]
fn rq_dag_deep_chain_ancestors() {
    let mut dag = BranchDag::new();
    let depth = 10;
    let mut prev = "trunk".to_string();
    for i in 0..depth {
        let name = format!("b{i}");
        dag.add_branch(BranchId::new(&name), vec![BranchId::new(&prev)])
            .unwrap();
        prev = name;
    }

    let leaf = format!("b{}", depth - 1);
    let ancestors = dag.ancestors(&BranchId::new(&leaf)).unwrap();
    assert_eq!(ancestors.len(), depth);
    assert!(ancestors.contains(&BranchId::new("trunk")));
}

// =========================================================================
// DIMENSION: checkpoint-risk
// =========================================================================

#[test]
fn rq_classify_all_risky_commands() {
    let risky = ["batch", "spawn", "remove", "cleanup", "rebase", "squash"];
    for cmd in &risky {
        assert_eq!(
            classify_command(cmd),
            OperationRisk::Risky,
            "'{cmd}' should be Risky"
        );
    }
}

#[test]
fn rq_classify_safe_commands_comprehensive() {
    let safe = [
        "list",
        "status",
        "context",
        "focus",
        "help",
        "version",
        "show",
        "doctor",
        "init",
        "create",
        "destroy",
        "checkpoint",
        "restore",
        "merge",
        "config",
        "info",
        "logs",
    ];
    for cmd in &safe {
        assert_eq!(
            classify_command(cmd),
            OperationRisk::Safe,
            "'{cmd}' should be Safe"
        );
    }
}

#[test]
fn rq_checkpoint_state_db_roundtrip_all() {
    for state in [
        CheckpointState::Pending,
        CheckpointState::Committed,
        CheckpointState::NeedsRestore,
    ] {
        let db_str = state.as_db();
        let parsed = CheckpointState::from_db(db_str).unwrap();
        assert_eq!(state, parsed, "roundtrip failed for {state:?}");
    }
}

#[test]
fn rq_checkpoint_record_equality_and_new() {
    let a = CheckpointRecord::new("cp-1".into(), true);
    let b = CheckpointRecord::new("cp-1".into(), true);
    let c = CheckpointRecord::new("cp-1".into(), false);
    assert_eq!(a, b);
    assert_ne!(a, c);
    assert!(a.committed);
    assert!(!c.committed);
}

#[test]
fn rq_operation_risk_needs_checkpoint() {
    assert!(!OperationRisk::Safe.needs_checkpoint());
    assert!(OperationRisk::Risky.needs_checkpoint());
}

// =========================================================================
// DIMENSION: hint-generation
// =========================================================================

use scp_isolate::{
    generate_hints, hints_for_error, next_actions_for_command, suggest_next_actions, ActionRisk,
    CommandContext, HintType, SystemState, WorkspaceInfo,
};

#[test]
fn rq_hints_conflict_and_merged_together() {
    let state = SystemState {
        workspaces: vec![
            WorkspaceInfo {
                id: "w1".into(),
                name: "conflicting".into(),
                state: WorkspaceState::Conflict,
            },
            WorkspaceInfo {
                id: "w2".into(),
                name: "done".into(),
                state: WorkspaceState::Merged,
            },
            WorkspaceInfo {
                id: "w3".into(),
                name: "active".into(),
                state: WorkspaceState::Working,
            },
        ],
        initialized: true,
    };
    let hints = generate_hints(&state);
    assert!(hints.iter().any(|h| h.hint_type == HintType::Warning));
    assert!(hints.iter().any(|h| h.hint_type == HintType::Tip));
    assert!(hints.iter().any(|h| h.hint_type == HintType::Info));
}

#[test]
fn rq_hints_for_error_known_codes() {
    let codes = [
        "WORKSPACE_EXISTS",
        "NOT_INITIALIZED",
        "WORKSPACE_NOT_FOUND",
        "CHECKPOINT_NOT_FOUND",
        "INVALID_STATE_TRANSITION",
    ];
    for code in &codes {
        let hints = hints_for_error(code, "test error");
        assert!(
            !hints.is_empty(),
            "hints_for_error('{code}') should return hints"
        );
    }
}

#[test]
fn rq_hints_for_error_extracts_name_from_quotes() {
    let hints = hints_for_error(
        "WORKSPACE_EXISTS",
        "Workspace 'my-workspace' already exists",
    );
    assert!(!hints.is_empty());
    // Should suggest a variant name
    let has_command = hints.iter().any(|h| {
        h.suggested_command
            .as_ref()
            .is_some_and(|c| c.contains("my-workspace"))
    });
    assert!(has_command, "hints should reference the workspace name");
}

#[test]
fn rq_suggest_next_actions_uninitialized_gives_init() {
    let state = SystemState {
        workspaces: vec![],
        initialized: false,
    };
    let actions = suggest_next_actions(&state);
    assert_eq!(actions.len(), 1);
    assert!(actions[0].commands[0].contains("init"));
}

#[test]
fn rq_suggest_next_actions_empty_gives_create() {
    let state = SystemState {
        workspaces: vec![],
        initialized: true,
    };
    let actions = suggest_next_actions(&state);
    assert!(!actions.is_empty());
    assert!(actions
        .iter()
        .any(|a| a.commands.iter().any(|c| c.contains("create"))));
}

#[test]
fn rq_next_actions_for_command_all_branches() {
    let commands = [
        "init",
        "create",
        "destroy",
        "list",
        "status",
        "checkpoint",
        "restore",
        "merge",
    ];
    for cmd in &commands {
        let ctx = CommandContext {
            command: cmd.to_string(),
            success: true,
            workspace_count: 1,
            workspace_name: Some("test-ws".into()),
        };
        let actions = next_actions_for_command(&ctx);
        // All known commands should return at least one action
        assert!(
            !actions.is_empty(),
            "next_actions_for_command('{cmd}') should return actions"
        );
    }
}

#[test]
fn rq_next_actions_for_command_error_branches() {
    let error_cmds = [
        "init",
        "create",
        "destroy",
        "status",
        "checkpoint",
        "restore",
        "merge",
    ];
    for cmd in &error_cmds {
        let ctx = CommandContext {
            command: cmd.to_string(),
            success: false,
            workspace_count: 0,
            workspace_name: None,
        };
        let actions = next_actions_for_command(&ctx);
        assert!(
            !actions.is_empty(),
            "error next_actions_for_command('{cmd}') should return recovery actions"
        );
    }
}

#[test]
fn rq_next_actions_unknown_command_returns_empty() {
    let ctx = CommandContext {
        command: "nonexistent-cmd".into(),
        success: true,
        workspace_count: 0,
        workspace_name: None,
    };
    let actions = next_actions_for_command(&ctx);
    assert!(actions.is_empty());
}

#[test]
fn rq_next_actions_destroy_with_many_workspaces_suggests_cleanup() {
    let ctx = CommandContext {
        command: "destroy".into(),
        success: true,
        workspace_count: 5,
        workspace_name: Some("destroyed-ws".into()),
    };
    let actions = next_actions_for_command(&ctx);
    assert!(actions
        .iter()
        .any(|a| a.commands.iter().any(|c| c.contains("clean"))));
}

#[test]
fn rq_next_actions_restore_has_risk_medium() {
    let ctx = CommandContext {
        command: "checkpoint".into(),
        success: true,
        workspace_count: 1,
        workspace_name: Some("ws".into()),
    };
    let actions = next_actions_for_command(&ctx);
    let has_medium = actions.iter().any(|a| a.risk == ActionRisk::Medium);
    assert!(has_medium, "restore suggestion should have Medium risk");
}

#[test]
fn rq_suggest_next_actions_conflict_gives_resolve() {
    let state = SystemState {
        workspaces: vec![WorkspaceInfo {
            id: "w".into(),
            name: "conflicted".into(),
            state: WorkspaceState::Conflict,
        }],
        initialized: true,
    };
    let actions = suggest_next_actions(&state);
    assert!(actions
        .iter()
        .any(|a| a.commands.iter().any(|c| c.contains("resolve"))));
}

// =========================================================================
// DIMENSION: type-invariants
// =========================================================================

#[test]
fn rq_workspace_state_serde_roundtrip_all() {
    for state in WorkspaceState::all() {
        let json = serde_json::to_string(state).unwrap();
        let parsed: WorkspaceState = serde_json::from_str(&json).unwrap();
        assert_eq!(*state, parsed, "serde roundtrip failed for {state:?}");
    }
}

#[test]
fn rq_workspace_state_from_str_case_insensitive() {
    let cases = [
        ("created", WorkspaceState::Created),
        ("WORKING", WorkspaceState::Working),
        ("ReAdY", WorkspaceState::Ready),
        ("MERGED", WorkspaceState::Merged),
        ("AbAnDoNeD", WorkspaceState::Abandoned),
        ("CONFLICT", WorkspaceState::Conflict),
    ];
    for (input, expected) in cases {
        let parsed = input.parse::<WorkspaceState>();
        assert!(
            parsed.is_ok(),
            "from_str('{input}') should parse to {expected:?}"
        );
        assert_eq!(parsed.unwrap(), expected);
    }
}

#[test]
fn rq_workspace_state_from_str_invalid() {
    let invalid = ["", "creating", "done", "open", "closed", "foo"];
    for s in &invalid {
        let result = s.parse::<WorkspaceState>();
        assert!(result.is_err(), "from_str('{s}') should fail");
    }
}

#[test]
fn rq_workspace_id_empty_rejected() {
    let result = WorkspaceId::parse(String::new());
    assert!(result.is_err());
}

#[test]
fn rq_bead_id_empty_rejected() {
    let result = BeadId::parse(String::new());
    assert!(result.is_err());
}

#[test]
fn rq_workspace_id_special_chars_accepted() {
    let cases = [
        "ws-with-dashes",
        "ws_with_underscores",
        "ws.with.dots",
        "ws/with/slashes",
    ];
    for s in cases {
        let result = WorkspaceId::parse(s.into());
        assert!(result.is_ok(), "WorkspaceId::parse('{s}') should succeed");
    }
}

#[test]
fn rq_bead_id_special_chars_accepted() {
    let cases = ["bead-123", "hq-abc", "ha-xyz", "gt-001"];
    for s in cases {
        let result = BeadId::parse(s.into());
        assert!(result.is_ok(), "BeadId::parse('{s}') should succeed");
    }
}

#[test]
fn rq_event_context_serde_with_all_fields() {
    let ctx = EventContext {
        workspace: "ws-test".into(),
        agent_id: Some("agent-42".into()),
        session_id: Some("session-7".into()),
    };
    let json = serde_json::to_string(&ctx).unwrap();
    let parsed: EventContext = serde_json::from_str(&json).unwrap();
    assert_eq!(ctx, parsed);
}

#[test]
fn rq_event_context_serde_minimal() {
    let ctx = EventContext {
        workspace: "w".into(),
        agent_id: None,
        session_id: None,
    };
    let json = serde_json::to_string(&ctx).unwrap();
    let parsed: EventContext = serde_json::from_str(&json).unwrap();
    assert_eq!(ctx, parsed);
}

#[test]
fn rq_event_type_all_returns_exactly_four() {
    assert_eq!(EventType::all().len(), 4);
}

#[test]
fn rq_event_type_display_all() {
    let expected = [
        (EventType::WorkspaceLifecycle, "workspace_lifecycle"),
        (EventType::Session, "session"),
        (EventType::Agent, "agent"),
        (EventType::Vcs, "vcs"),
    ];
    for (et, name) in &expected {
        assert_eq!(et.to_string(), *name);
    }
}

#[test]
fn rq_checkpoint_state_invalid_db_strings() {
    let invalid = ["", "active", "done", "deleted", "PENDING", "Pending"];
    for s in &invalid {
        let result = CheckpointState::from_db(s);
        assert!(
            result.is_err(),
            "CheckpointState::from_db('{s}') should fail"
        );
    }
}
